# Generated by Django 2.2 on 2019-04-19 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190419_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ziomek',
            fields=[
                ('email_id', models.EmailField(blank=True, max_length=80, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference', models.CharField(max_length=20)),
                ('email_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to='api.Ziomek')),
            ],
        ),
    ]
