# Generated by Django 2.2 on 2019-04-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190419_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='isCorrect',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='IsCorrect',
        ),
    ]
